### ISSUE TITLE
Adding multiple songs

### ISSUE THREAD

**Issue by ghost** [Kaufisch/Discord_24-7_MusicBot#2]
So I'm trying to add multiple songs in the playlist.txt file but seems like it's not working. Does there need to be a space or something between each URL?

**Comment by jruehlow** [comment]
Every url/title has to be in a new line eg.:
`Kaufisch - Fill your playlist with songs;https://youtu.be/ctGOaiHP4dE`
`Kaufisch - Fill your playlist with songs;https://youtu.be/ctGOaiHP4dE`
